import type { Metadata } from "next";
import { Outfit as FontOutfit } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";

const fontOutfit = FontOutfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased w-full mx-auto max-w-screen-2xl",
          "md:px-6 md:py-6",
          "lg:py-8",
          fontOutfit.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <section
            className={cn(
              "min-h-screen w-full flex justify-center px-6 mt-12",
              "md:mt-24"
            )}
          >
            {children}
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
