import type { Metadata } from "next";
import { Outfit as FontOutfit } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";

import { NavBar } from "@/components/navbar";
import { SearchBar } from "@/components/searchbar";

const fontOutfit = FontOutfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: Implement dynamic placeholder

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased w-full mx-auto max-w-screen-2xl",
          "md:px-6 md:py-6",
          "lg:py-8",
          fontOutfit.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className={cn(
              "flex flex-col",
              "lg:flex-row lg:space-x-9 lg:max-w-[1440px]"
            )}
          >
            <NavBar />
            <main className={cn("lg:pl-24")}>
              <SearchBar placeholder="Search for movies or TV series" />
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
